export default {
  PORT: Number(process.env.TALENTS_PORT) ?? 8000,
  NODE_ENV: process.env.TALENTS_NODE_ENV,
  API_PREFIX: process.env.TALENTS_API_PREFIX ?? "api/v1",

  DB_USER: process.env.TALENTS_DB_USER,
  DB_HOST: process.env.TALENTS_DB_HOST,
  DB_PORT: process.env.TALENTS_DB_PORT,
  DB_PASSWORD: process.env.TALENTS_DB_PASSWORD,
  DB_NAME: process.env.TALENTS_DB_NAME,
  DATABASE_URL: process.env.TALENTS_DATABASE_URL,
  BASE_URL: process.env.TALENTS_BASE_URL ?? "https://talents-api.enyata.com",
  FRONTEND_URL:
    process.env.TALENTS_FRONTEND_URL ?? "https://talents.enyata.com",

  ACCESS_TOKEN_TTL: process.env.TALENTS_ACCESS_TOKEN_TTL || "15m",
  REFRESH_TOKEN_TTL: process.env.TALENTS_REFRESH_TOKEN_TTL || "7d",

  ACCESS_TOKEN_PUBLIC_KEY: process.env.TALENTS_ACCESS_TOKEN_PUBLIC_KEY,
  REFRESH_TOKEN_PUBLIC_KEY: process.env.TALENTS_REFRESH_TOKEN_PUBLIC_KEY,
  ACCESS_TOKEN_PRIVATE_KEY: process.env.TALENTS_ACCESS_TOKEN_PRIVATE_KEY,
  REFRESH_TOKEN_PRIVATE_KEY: process.env.TALENTS_REFRESH_TOKEN_PRIVATE_KEY,

  COOKIE_EXPIRES: process.env.TALENTS_COOKIE_EXPIRES || "7d",
  SWAGGER_JSON_URL: process.env.TALENTS_SWAGGER_JSON_URL,

  GOOGLE_CLIENT_ID: process.env.TALENTS_GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.TALENTS_GOOGLE_CLIENT_SECRET,

  LINKEDIN_CLIENT_ID: process.env.TALENTS_LINKEDIN_CLIENT_ID,
  LINKEDIN_CLIENT_SECRET: process.env.TALENTS_LINKEDIN_CLIENT_SECRET,

  EMAIL_PROVIDER: process.env.TALENTS_EMAIL_PROVIDER || "gmail",
  EMAIL_FROM: process.env.TALENTS_EMAIL_FROM || "noreply@talents.enyata.com",

  SMTP_HOST: process.env.TALENTS_SMTP_HOST || "smtp.mailtrap.io",
  SMTP_PORT: parseInt(process.env.TALENTS_SMTP_PORT || "2525"),
  SMTP_SECURE: process.env.TALENTS_SMTP_SECURE === "true",
  SMTP_USER: process.env.TALENTS_SMTP_USER || "",
  SMTP_PASSWORD: process.env.TALENTS_SMTP_PASSWORD || "",

  SENDGRID_USERNAME: process.env.TALENTS_SENDGRID_USERNAME || "",
  SENDGRID_PASSWORD: process.env.TALENTS_SENDGRID_PASSWORD || "",

  GMAIL_USER: process.env.TALENTS_GMAIL_USER || "",
  GMAIL_PASSWORD: process.env.TALENTS_GMAIL_PASSWORD || "",

  REDIS_URL: process.env.TALENTS_REDIS_URL || "redis://localhost:6379",
  REDIS_CACHE_TTL_LONG:
    Number(process.env.TALENTS_REDIS_CACHE_TTL_LONG) || 60 * 60, // 1 hour
  REDIS_CACHE_TTL_SHORT:
    Number(process.env.TALENTS_REDIS_CACHE_TTL_SHORT) || 60 * 5, // 5 minutes
};
